<?php
/**
 * @author    Manuel Cánepa <manuel@gento.com.ar>
 * @copyright GENTo (https://gento.com.ar) Todos los derechos reservados
 */

?>
<?php
/** @var \Gento\TangoTiendas\Block\Adminhtml\Order\View\Tab\Notifications $block */

/** @var \Magento\Framework\Escaper $escaper */
?>
<section class="admin__page-section edit-order-notifications">
    <div class="edit-order-notifications-block">
        <?php foreach ($block->getFullHistory() as $_item) : ?>
            <div class="notifications-block-item">
                <div class="notifications-block-item-comment"
                     data-mage-init='{"tangoJsonViewer": {
                        "data": <?= /* @noEscape */ $_item->getJsonData() ?>,
                        "createdAt": "<?= /* @noEscape */ $_item->getCreatedAt() ?>",
                        "collapsible": false
                     }}'>
                </div>
            </div>
            <hr/>
        <?php endforeach; ?>
        <?php if (count($block->getFullHistory()) === 0) : ?>
            <div class="notifications-block-item">
                <div class="notifications-block-item-comment">
                    <?= $escaper->escapeHtml(__('No tango notification was found')) ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
</section>
