language: php
php:
  - 7.2
  - 7.3
  - 7.4
services:
  - mysql
  - redis-server
  - elasticsearch
before_script:
  - composer global config http-basic.repo.magento.com "$COMPOSER_MAGENTO_USER" "$COMPOSER_MAGENTO_PASSWORD"
  - composer install
script:
  - bin/magento setup:install --backend-frontname admin --base-url=http://magento24.local/ \
    --db-host localhost --db-user travis --db-name magento \
    --session-save   redis  --session-save-redis-host    localhost  --session-save-redis-db   0 \
    --cache-backend  redis  --cache-backend-redis-server localhost  --cache-backend-redis-db  1 \
    --page-cache     redis  --page-cache-redis-server    localhost  --page-cache-redis-db     2 \
    --elasticsearch-host 127.0.0.1 --elasticsearch-port 9200 \
    --admin-user admin --admin-password Admin123 --admin-firstname admin --admin-lastname Admin \
    --admin-email admin@admin.com
  - bin/magento deploy:mode:set -s production
  - bin/magento setup:di:compile

